name: minim
channels:
  - conda-forge
  - microsoft
dependencies:
  # CORE DEPENDENCIES
  - cryptography
  - httpx
  # OPTIONAL DEPENDENCIES
  - ffmpeg
  - pytest-playwright
  # DEVELOPMENT DEPENDENCIES
  - pytest-cov
  - ruff
  # DOCUMENTATION DEPENDENCIES
  - numpydoc
  - shibuya
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  - sphinx-togglebutton